### ISSUE TITLE
Spoiler alert 🫣

### ISSUE THREAD

**Issue by johnspurlock** [MierenManz/v8_format#8]
https://chromium.googlesource.com/v8/v8/+/refs/heads/main/src/objects/value-serializer.cc

that `0x0F` (version = 15) gives away you're using a relatively recent version of Node or Deno : )

**Comment by nhrones** [comment]
v8 serialization returns a two byte Version header - the VERSION flag 0xff followed by the current serialization version number; currently at 0x0f (15). Any major change would need to be handled by all concerned.

The version number is specific to the v8 value-serialization version only.  It is not tied to a v8 version!

From the v8 source -- value-serializer.cc

```c
// Version 9: (imported from Blink)
// Version 10: one-byte (Latin-1) strings
// Version 11: properly separate undefined from the hole in arrays
// Version 12: regexp and string objects share normal string encoding
// Version 13: host objects have an explicit tag (rather than handling all
//             unknown tags)
// Version 14: flags for JSArrayBufferViews
// Version 15: support for shared objects with an explicit tag
//
// WARNING: Increasing this value is a change which cannot safely be rolled
// back without breaking compatibility with data stored on disk. It is
// strongly recommended that you do not make such changes near a release
// milestone branch point.
//
// Recent changes are routinely reverted in preparation for branch, and this
// has been the cause of at least one bug in the past.
static const uint32_t kLatestVersion = 15;
```

**Comment by MierenManz** [comment]
I don't think it gives away anything. ~~`kLatestVersion` has been at 15 since the first commit of this repository . The latest deno version was 1.30.2. That's more than 7 minor updates ago. I feel like this is not a problem in any sort of way~~
Edit: The last time `kLatestVersion` got updated was on january 26 2022. The latest deno version was 1.19.0 back then. That's 18 minors ago. Definitely not a problem in any sort of way
